<?php

namespace ContainerP2ea1NS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H4CqBqSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h4CqBqS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h4CqBqS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'film' => ['privates', '.errored..service_locator.h4CqBqS.App\\Entity\\Film', NULL, 'Cannot autowire service ".service_locator.h4CqBqS": it references class "App\\Entity\\Film" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'film' => 'App\\Entity\\Film',
        ]);
    }
}
