<?php

namespace ContainerP2ea1NS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AxwEccdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AxwEccd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AxwEccd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cinema' => ['privates', '.errored..service_locator.AxwEccd.App\\Entity\\Cinema', NULL, 'Cannot autowire service ".service_locator.AxwEccd": it references class "App\\Entity\\Cinema" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cinema' => 'App\\Entity\\Cinema',
            'entityManager' => '?',
        ]);
    }
}
