<?php

namespace ContainerP2ea1NS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h4CqBqS.App\Entity\Film' shared service.
     *
     * @return \App\Entity\Film
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.h4CqBqS": it references class "App\\Entity\\Film" but no such service exists.');
    }
}
