<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Film extends \App\Entity\Film implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Affiche' => [parent::class, 'Affiche', null],
        "\0".parent::class."\0".'Age' => [parent::class, 'Age', null],
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null],
        "\0".parent::class."\0".'Genre' => [parent::class, 'Genre', null],
        "\0".parent::class."\0".'Nom' => [parent::class, 'Nom', null],
        "\0".parent::class."\0".'Note' => [parent::class, 'Note', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'label' => [parent::class, 'label', null],
        "\0".parent::class."\0".'seances' => [parent::class, 'seances', null],
        'Affiche' => [parent::class, 'Affiche', null],
        'Age' => [parent::class, 'Age', null],
        'Description' => [parent::class, 'Description', null],
        'Genre' => [parent::class, 'Genre', null],
        'Nom' => [parent::class, 'Nom', null],
        'Note' => [parent::class, 'Note', null],
        'id' => [parent::class, 'id', null],
        'label' => [parent::class, 'label', null],
        'seances' => [parent::class, 'seances', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
