<?php

namespace ContainerBssacYL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yweh0LlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yweh0Ll' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yweh0Ll'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cinema' => ['privates', '.errored..service_locator.Yweh0Ll.App\\Entity\\Cinema', NULL, 'Cannot autowire service ".service_locator.Yweh0Ll": it references class "App\\Entity\\Cinema" but no such service exists.'],
        ], [
            'cinema' => 'App\\Entity\\Cinema',
        ]);
    }
}
