<?php

namespace ContainerBssacYL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCinema2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yweh0Ll.App\Entity\Cinema' shared service.
     *
     * @return \App\Entity\Cinema
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Yweh0Ll": it references class "App\\Entity\\Cinema" but no such service exists.');
    }
}
