<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBssacYL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBssacYL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBssacYL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBssacYL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBssacYL\App_KernelDevDebugContainer([
    'container.build_hash' => 'BssacYL',
    'container.build_id' => '46f6ce7a',
    'container.build_time' => 1721582263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBssacYL');
